epochs: 10
num_class: 10
data_dir: 'numta'
output_dir: 'output'
train_batch: 128
valid_batch: 128
lr: 0.001
debug: true
model:
  - [Conv2D, [3, 6, 5, 1, 0]] # in_channels, out_channels, kernel_size, stride=1, padding=0, bias=True
  - [ReLU, []] 
  - [MaxPool2D, [2, 2]]
  - [Conv2D, [6, 16, 5, 1, 0]] 
  - [ReLU, []] 
  - [MaxPool2D, [2, 2]]
  - [Flatten, []] # 64 * 5 * 5
  - [Linear, [120]] # 
  - [ReLU, []] # 26
  - [Linear, [84]] # 
  - [ReLU, []] # 26
  - [Linear, [10]] #  
  - [Softmax, []]
checkpoint_path: "output/best_model_E1.npy"
resume: true
gt_csv: "numta/training-e.csv"
augment:
  img_shape: [48, 48]
  use_bbox: true
  reverse: true
  aug: false
  dilation: true
  opening: false
  mixup: 0.0
  contour_cutout_prob: 1.0
  contour_cutout_number: 5
  cache: true
lr_scheduler:
  factor: 0.7
  patience: 2
use_wandb: false
wandb:
  project: "cse472_cnn_scratch"
  entity: "nexh98" # anonymous
notebook: ''
name: 'Model1-Baseline'
comment: 'Model1-64x64'
exp: 'Baseline'

# epochs: 10
# num_class: 10
# data_dir: 'numta'
# output_dir: 'output'
# train_batch: 128
# valid_batch: 128
# lr: 0.001
# debug: false
# model:
#   - [Conv2D, [3, 16, 3, 1, 1]] # in_channels, out_channels, kernel_size, stride=1, padding=0, bias=True
#   - [ReLU, []] 
#   - [MaxPool2D, [2, 2]]
#   - [Conv2D, [16, 32, 3, 1, 1]] 
#   - [ReLU, []] 
#   - [MaxPool2D, [2, 2]]
#   - [Conv2D, [32, 32, 3, 1, 1]] 
#   - [ReLU, []] # 26
#   - [MaxPool2D, [2, 2]] # kernel_size, stride=1 -> 13
#   - [Flatten, []] # 64 * 5 * 5
#   - [Linear, [1024]] # 
#   - [ReLU, []] # 26
#   - [Linear, [512]] # 
#   - [ReLU, []] # 26
#   - [Linear, [10]] #  
#   - [Softmax, []]
# checkpoint_path: "ModelLenet_reverse_E54.npy"
# gt_csv: "numta/training-e.csv"
# augment:
#   img_shape: [64, 64]
#   use_bbox: true
#   reverse: false
#   aug: false
#   dilation: true
#   opening: false
#   mixup: 0.0
#   cache: true
# lr_scheduler:
#   factor: 0.7
#   patience: 2
# use_wandb: false
# wandb:
#   project: "cse472_cnn_scratch"
#   entity: "nexh98" # anonymous
# notebook: ''
# name: 'Model1-Baseline'
# comment: 'Model1-64x64'
# exp: 'Baseline'


# model 2
# model:
#   - [Conv2D, [1, 6, 5, 1, 0]] # in_channels, out_channels, kernel_size, stride=1, padding=0, bias=True
#   - [ReLU, []] 
#   - [MaxPool2D, [2, 2]]
#   - [Conv2D, [6, 16, 5, 1, 0]] 
#   - [ReLU, []] 
#   - [MaxPool2D, [2, 2]]
#   - [Conv2D, [16, 32, 3, 1, 1]] 
#   - [ReLU, []] 
#   - [MaxPool2D, [2, 2]]
#   - [Flatten, []] # 64 * 5 * 5
#   - [Linear, [120]] # 
#   - [ReLU, []] # 26
#   - [Linear, [84]] # 
#   - [ReLU, []] # 26
#   - [Linear, [10]] #  
#   - [Softmax, []]
# augment:
#   img_shape: [48, 48]
#   use_bbox: false
#   reverse: false
#   aug: false
#   dilation: false
#   opening: false
#   mixup: 0.0
#   cache: true

# model 3
# model:
#   - [Conv2D, [1, 16, 3, 1, 1]] # in_channels, out_channels, kernel_size, stride=1, padding=0, bias=True
#   - [ReLU, []] 
#   - [MaxPool2D, [2, 2]]
#   - [Conv2D, [16, 32, 3, 1, 1]] 
#   - [ReLU, []] 
#   - [MaxPool2D, [2, 2]]
#   - [Conv2D, [32, 32, 3, 1, 1]] 
#   - [ReLU, []] # 26
#   - [MaxPool2D, [2, 2]] # kernel_size, stride=1 -> 13
#   - [Flatten, []] # 64 * 5 * 5
#   - [Linear, [1024]] # 
#   - [ReLU, []] # 26
#   - [Linear, [512]] # 
#   - [ReLU, []] # 26
#   - [Linear, [10]] #  
#   - [Softmax, []]
# augment:
#   img_shape: [48, 48]
#   use_bbox: false
#   reverse: false
#   aug: false
#   dilation: false
#   opening: false
#   mixup: 0.0
#   cache: true